try {
    console.log(name);

    const name = "Thyago Franco";

    
} catch (err) {
    console.log("Error" ,err )
}


console.log("Keeping runing...")